spring.datasource:
  url: jdbc:mariadb://localhost:3306/InvoiceDatabase?createDatabaseIfNotExist=true
  username: root
  password: cM5HGe2RV-9v6Veh
  driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true
